//HintName: PureES.EventHandlers.Events_CreatedEventHandler_PureESTestsModelsTestEventHandlers_OnCreated2.g.cs
// <auto-generated/>

// This file was automatically generated by the PureES source generator.
// Do not edit this file manually since it will be automatically overwritten.
// ReSharper disable All

#nullable disable
#pragma warning disable CS0162 //Unreachable code detected

#pragma warning disable CS8019 //Unnecessary using directive
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;


namespace PureES.EventHandlers
{
    ///<summary><c>PureES.Tests.Models.TestEventHandlers.OnCreated2</c></summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PureES.SourceGenerator", "1.0.0.0")]
    internal class Events_CreatedEventHandler_PureESTestsModelsTestEventHandlers_OnCreated2 : global::PureES.IEventHandler<PureES.Tests.Models.Events.Created>
    {
        private readonly global::Microsoft.Extensions.Logging.ILogger<Events_CreatedEventHandler_PureESTestsModelsTestEventHandlers_OnCreated2> _logger;
        private readonly global::PureES.PureESEventHandlerOptions _options;
        private readonly global::Microsoft.Extensions.Logging.ILoggerFactory _service0;
        private readonly global::PureES.Tests.Models.TestEventHandlers _parent;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Events_CreatedEventHandler_PureESTestsModelsTestEventHandlers_OnCreated2(
            global::Microsoft.Extensions.Logging.ILoggerFactory service0,
            global::PureES.Tests.Models.TestEventHandlers parent,
            global::Microsoft.Extensions.Options.IOptions<PureES.PureESOptions> options,
            global::Microsoft.Extensions.Logging.ILogger<Events_CreatedEventHandler_PureESTestsModelsTestEventHandlers_OnCreated2> logger = null)
        {
            this._options = options?.Value.EventHandlers ?? throw new ArgumentNullException(nameof(options));
            this._logger = logger ?? global::Microsoft.Extensions.Logging.Abstractions.NullLogger<Events_CreatedEventHandler_PureESTestsModelsTestEventHandlers_OnCreated2>.Instance;
            this._service0 = service0 ?? throw new ArgumentNullException(nameof(service0));
            this._parent = parent ?? throw new ArgumentNullException(nameof(parent));
        }
        private static readonly global::System.Type ParentType = typeof(global::PureES.Tests.Models.TestEventHandlers);
        private static readonly global::System.Type EventType = typeof(global::PureES.Tests.Models.Events.Created);
        private static readonly global::System.Reflection.MethodInfo _method = ParentType.GetMethod(name: "OnCreated2", bindingAttr: global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance, types: new [] { typeof(global::PureES.EventEnvelope<global::PureES.Tests.Models.Events.Created, object>), typeof(global::Microsoft.Extensions.Logging.ILoggerFactory) });

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public global::System.Reflection.MethodInfo Method
        {

            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => _method ?? throw new InvalidOperationException($"Could not locate method 'OnCreated2' on {ParentType}");
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public int Priority
        {

            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            get => 0;
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static double GetElapsed(long start)
        {
#if NET7_0_OR_GREATER
            return global::System.Diagnostics.Stopwatch.GetElapsedTime(start).TotalMilliseconds;
#else
            return (global::System.Diagnostics.Stopwatch.GetTimestamp() - start) * 1000 / (double)global::System.Diagnostics.Stopwatch.Frequency;
#endif
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static TimeSpan GetElapsedTimespan(long start)
        {
#if NET7_0_OR_GREATER
            return global::System.Diagnostics.Stopwatch.GetElapsedTime(start);
#else
            return global::System.TimeSpan.FromSeconds((global::System.Diagnostics.Stopwatch.GetTimestamp() - start) / (double)global::System.Diagnostics.Stopwatch.Frequency);
#endif
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Threading.Tasks.Task Handle(global::PureES.EventEnvelope @event)
        {
#if NET6_0_OR_GREATER
            global::System.ArgumentNullException.ThrowIfNull(@event, nameof(@event));
#else
            if (@event is null) throw new global::System.ArgumentNullException(nameof(@event));
#endif
            if (@event.Event is not global::PureES.Tests.Models.Events.Created)
            {
                throw new ArgumentOutOfRangeException($"Unknown event type {@event.Event.GetType()}", nameof(@event));
            }
            using (var activity = PureES.PureESTracing.ActivitySource.StartActivity("HandleEvent"))
            {
                if (activity != null)
                {
                    activity.DisplayName = "HandleEvent TestEventHandlers.OnCreated2 (Events+Created)";
                    if (activity.IsAllDataRequested)
                    {
                        activity?.SetTag("StreamId", @event.StreamId);
                        activity?.SetTag("StreamPosition", @event.StreamPosition);
                        activity?.SetTag("HandlerClass", "PureES.Tests.Models.TestEventHandlers");
                        activity?.SetTag("HandlerMethod", "OnCreated2");
                        activity?.SetTag("HandlerEventType", "PureES.Tests.Models.Events.Created");
                        activity?.SetTag("EventType", global::PureES.BasicEventTypeMap.GetTypeName(@event.Event.GetType()));
                    }
                }
                using (_logger.BeginScope(new global::System.Collections.Generic.Dictionary<string, object>()
                    {
                        { "StreamId", @event.StreamId },
                        { "StreamPosition", @event.StreamPosition },
                        { "HandlerClass", "PureES.Tests.Models.TestEventHandlers" },
                        { "HandlerMethod", "OnCreated2" },
                        { "HandlerEventType", "PureES.Tests.Models.Events.Created" },
                        { "EventType", global::PureES.BasicEventTypeMap.GetTypeName(@event.Event.GetType()) },
                    }))
                {
                    var ct = new CancellationTokenSource(_options.Timeout).Token;
                    var start = global::System.Diagnostics.Stopwatch.GetTimestamp();
                    try
                    {
                        this._logger.Log(
                            logLevel: global::Microsoft.Extensions.Logging.LogLevel.Debug,
                            exception: null,
                            message: "Handling event {StreamId}/{StreamPosition}. Event Type: {@EventType}. Event handler {EventHandler} on {@EventHandlerParent}",
                            @event.StreamId,
                            @event.StreamPosition,
                            @event.Event.GetType(),
                            "OnCreated2",
                            ParentType);
                        if (this._options.RetryPolicy != null)
                        {
                            this._options.RetryPolicy.Execute(() => 
                                this._parent.OnCreated2(
                                    new global::PureES.EventEnvelope<global::PureES.Tests.Models.Events.Created, object>(@event),
                                    this._service0));
                        }
                        else
                        {
                            this._parent.OnCreated2(
                                new global::PureES.EventEnvelope<global::PureES.Tests.Models.Events.Created, object>(@event),
                                this._service0);
                        }
                        var elapsed = GetElapsedTimespan(start);
                        this._logger.Log(
                            logLevel: this._options.GetLogLevel(@event, elapsed),
                            exception: null,
                            message: "Handled event {StreamId}/{StreamPosition}. Elapsed: {Elapsed:0.0000}ms. Event Type: {@EventType}. Event handler {EventHandler} on {@EventHandlerParent}",
                            @event.StreamId,
                            @event.StreamPosition,
                            elapsed.TotalMilliseconds,
                            @event.Event.GetType(),
                            "OnCreated2",
                            ParentType);
                        return global::System.Threading.Tasks.Task.CompletedTask;
                    }
                    catch (global::System.Exception ex)
                    {
                        this._logger.Log(
                            logLevel: this._options.PropagateExceptions ? LogLevel.Information : LogLevel.Error,
                            exception: ex,
                            message: "Error handling event {StreamId}/{StreamPosition}. Elapsed: {Elapsed:0.0000}ms. Event Type: {@EventType}. Event handler {EventHandler} on {@EventHandlerParent}",
                            @event.StreamId,
                            @event.StreamPosition,
                            GetElapsed(start),
                            @event.Event.GetType(),
                            "OnCreated2",
                            ParentType);
                        if (activity != null)
                        {
                            activity.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, ex.Message);
                            activity.SetTag("error.type", ex.GetType().FullName);
                            activity.AddException(ex);
                        }
                        if (this._options.PropagateExceptions)
                        {
                            throw;
                        }
                    }
                }
            }
        }
    }
}
