//HintName: PureES.AggregateFactories.ImplementedGenericAggregateFactory.g.cs
// <auto-generated/>

// This file was automatically generated by the PureES source generator.
// Do not edit this file manually since it will be automatically overwritten.
// ReSharper disable All

#nullable disable
#pragma warning disable CS0162 //Unreachable code detected

#pragma warning disable CS8019 //Unnecessary using directive
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;


namespace PureES.AggregateFactories
{
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PureES.SourceGenerator", "1.0.0.0")]
    internal sealed class ImplementedGenericAggregateFactory : global::PureES.IAggregateFactory<global::PureES.Tests.Models.ImplementedGenericAggregate>
    {
        private readonly global::PureES.IEventStore _eventStore;
        private readonly global::System.IServiceProvider _services;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ImplementedGenericAggregateFactory(
            global::PureES.IEventStore eventStore,
            global::System.IServiceProvider services)
        {
            this._eventStore = eventStore ?? throw new ArgumentNullException(nameof(eventStore));
            this._services = services ?? throw new ArgumentNullException(nameof(services));
        }
        private static readonly global::System.Type AggregateType = typeof(global::PureES.Tests.Models.ImplementedGenericAggregate);

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private async Task<global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate>> CreateWhen(string streamId, global::System.Collections.Generic.IAsyncEnumerator<global::PureES.EventEnvelope> enumerator, CancellationToken ct)
        {
            if (!await enumerator.MoveNextAsync())
            {
                throw new ArgumentException("Stream is empty");
            }
            global::PureES.Tests.Models.ImplementedGenericAggregate current;
            switch (enumerator.Current.Event)
            {
                case object e:
                {
                    try
                    {
                        current = global::PureES.Tests.Models.ImplementedGenericAggregate.When(e);
                    }
                    catch (Exception ex)
                    {
                        throw new global::PureES.RehydrationException(streamId, AggregateType, "PureES.Tests.Models.TestGenericAggregate<PureES.Tests.Models.ImplementedGenericAggregate, object, object>.When(object)", ex);
                    }
                    break;
                }
                default:
                {
                    var eventType = global::PureES.BasicEventTypeMap.GetTypeName(enumerator.Current.Event.GetType());
                    throw new global::PureES.RehydrationException(streamId, AggregateType, $"No suitable CreateWhen method found for event '{eventType}'");
                }
            }
            return new global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate>(current, 0ul);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private async Task<global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate>> UpdateWhen(string streamId, global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate> aggregate, global::System.Collections.Generic.IAsyncEnumerator<global::PureES.EventEnvelope> enumerator, CancellationToken ct)
        {
            global::PureES.Tests.Models.ImplementedGenericAggregate current = aggregate.Aggregate;
            var revision = aggregate.StreamPosition;
            while (await enumerator.MoveNextAsync())
            {
                switch (enumerator.Current.Event)
                {
                    default:
                    {
                        var eventType = global::PureES.BasicEventTypeMap.GetTypeName(enumerator.Current.Event.GetType());
                        throw new global::PureES.RehydrationException(streamId, AggregateType, $"No suitable UpdateWhen method found for event '{eventType}'");
                    }
                }
                ++revision;
            }
            return new global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate>(current, revision);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public async Task<global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate>> Create(string streamId, global::System.Collections.Generic.IAsyncEnumerable<global::PureES.EventEnvelope> @events, CancellationToken cancellationToken)
        {
            await using (var enumerator = @events.GetAsyncEnumerator(cancellationToken))
            {
                var current = await CreateWhen(streamId, enumerator, cancellationToken);
                return await UpdateWhen(streamId, current, enumerator, cancellationToken);
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public async Task<global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate>> Update(string streamId, global::PureES.RehydratedAggregate<global::PureES.Tests.Models.ImplementedGenericAggregate> aggregate, global::System.Collections.Generic.IAsyncEnumerable<global::PureES.EventEnvelope> @events, CancellationToken cancellationToken)
        {
            await using (var enumerator = @events.GetAsyncEnumerator(cancellationToken))
            {
                return await UpdateWhen(streamId, aggregate, enumerator, cancellationToken);
            }
        }
    }
}
