//HintName: PureES.AggregateStores.AggregateAggregateStore.g.cs
// <auto-generated/>
// This file was automatically generated by the PureES source generator.
// Do not edit this file manually since it will be automatically overwritten.
// ReSharper disable All

#nullable disable

using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace PureES.AggregateStores
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PureES.SourceGenerator", "1.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal class AggregateAggregateStore : global::PureES.Core.IAggregateStore<global::PureES.Core.Tests.Models.TestAggregates.Aggregate>
    {
        private readonly global::PureES.Core.EventStore.IEventStore _eventStore;
        private readonly global::Microsoft.Extensions.Logging.ILoggerFactory _service0;
        private readonly global::System.IServiceProvider _service1;

        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AggregateAggregateStore(
            global::Microsoft.Extensions.Logging.ILoggerFactory service0,
            global::System.IServiceProvider service1,
            global::PureES.Core.EventStore.IEventStore eventStore)
        {
            this._eventStore = eventStore ?? throw new ArgumentNullException(nameof(eventStore));
            this._service0 = service0 ?? throw new ArgumentNullException(nameof(service0));
            this._service1 = service1 ?? throw new ArgumentNullException(nameof(service1));
        }

        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregates.Aggregate> Load(string streamId, CancellationToken cancellationToken)
        {
            var @events = this._eventStore.Read(global::PureES.Core.EventStore.Direction.Forwards, streamId, cancellationToken);
            return Create(@events, cancellationToken);
        }

        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregates.Aggregate> Load(string streamId, ulong expectedRevision, CancellationToken cancellationToken)
        {
            var @events = this._eventStore.Read(global::PureES.Core.EventStore.Direction.Forwards, streamId, expectedRevision, cancellationToken);
            return Create(@events, cancellationToken);
        }

        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregates.Aggregate> LoadPartial(string streamId, ulong requiredRevision, CancellationToken cancellationToken)
        {
            var @events = this._eventStore.ReadPartial(global::PureES.Core.EventStore.Direction.Forwards, streamId, requiredRevision, cancellationToken);
            return Create(@events, cancellationToken);
        }

        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public async global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregates.Aggregate> Create(global::System.Collections.Generic.IAsyncEnumerable<global::PureES.Core.EventEnvelope> @events, CancellationToken cancellationToken)
        {
            await using (var enumerator = @events.GetAsyncEnumerator(cancellationToken))
            {
                if (!await enumerator.MoveNextAsync())
                {
                    throw new ArgumentException("Stream is empty", nameof(@events));
                }
                global::PureES.Core.Tests.Models.TestAggregates.Aggregate aggregate;
                switch (enumerator.Current.Event)
                {
                    case global::PureES.Core.Tests.Models.Events.Created e:
                    {
                        aggregate = global::PureES.Core.Tests.Models.TestAggregates.Aggregate.When(
                            new global::PureES.Core.EventEnvelope<global::PureES.Core.Tests.Models.Events.Created, global::PureES.Core.Tests.Models.TestAggregates.Metadata>(enumerator.Current));
                        break;
                    }
                    default:
                    {
                        var eventType = enumerator.Current.Event.GetType().FullName;
                        throw new NotImplementedException($"No suitable CreateWhen method found for event {eventType}");
                    }
                }
                aggregate.GlobalWhen(enumerator.Current, cancellationToken);
                await aggregate.GlobalWhenAsync(enumerator.Current, this._service0);
                while (await enumerator.MoveNextAsync())
                {
                    switch (enumerator.Current.Event)
                    {
                        case global::PureES.Core.Tests.Models.Events.Created e:
                        {
                            aggregate.set_Created(
                                new global::PureES.Core.EventEnvelope<global::PureES.Core.Tests.Models.Events.Created, global::PureES.Core.Tests.Models.TestAggregates.Metadata>(enumerator.Current));
                            break;
                        }
                        case global::PureES.Core.Tests.Models.Events.Updated e:
                        {
                            aggregate.When(e, this._service1);
                            break;
                        }
                        case int e:
                        {
                            await aggregate.When(
                                new global::PureES.Core.Tests.Models.TestAggregates.EventEnvelope<int>(enumerator.Current),
                                this._service0);
                            break;
                        }
                        default:
                        {
                            var eventType = enumerator.Current.Event.GetType().FullName;
                            throw new NotImplementedException($"No suitable UpdateWhen method found for event {eventType}");
                        }
                    }
                    aggregate.GlobalWhen(enumerator.Current, cancellationToken);
                    await aggregate.GlobalWhenAsync(enumerator.Current, this._service0);
                }
                return aggregate;
            }
        }
    }
}
