//HintName: PureES.AggregateStores.TestAggregateAggregateStore.g.cs
// <auto-generated/>

// This file was automatically generated by the PureES source generator.
// Do not edit this file manually since it will be automatically overwritten.
// ReSharper disable All

#nullable disable
#pragma warning disable CS0162 //Unreachable code detected

using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;

namespace PureES.AggregateStores
{
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PureES.SourceGenerator", "1.0.0.0")]
    internal class TestAggregateAggregateStore : global::PureES.Core.IAggregateStore<global::PureES.Core.Tests.Models.TestAggregate>
    {
        private readonly global::PureES.Core.IEventStore _eventStore;
        private readonly global::System.IServiceProvider _services;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TestAggregateAggregateStore(
            global::PureES.Core.IEventStore eventStore,
            global::System.IServiceProvider services)
        {
            this._eventStore = eventStore ?? throw new ArgumentNullException(nameof(eventStore));
            this._services = services ?? throw new ArgumentNullException(nameof(services));
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregate> Load(string streamId, CancellationToken cancellationToken)
        {
            var @events = this._eventStore.Read(global::PureES.Core.Direction.Forwards, streamId, cancellationToken);
            return Create(@events, cancellationToken);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregate> Load(string streamId, ulong expectedRevision, CancellationToken cancellationToken)
        {
            var @events = this._eventStore.Read(global::PureES.Core.Direction.Forwards, streamId, expectedRevision, cancellationToken);
            return Create(@events, cancellationToken);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregate> LoadPartial(string streamId, ulong requiredRevision, CancellationToken cancellationToken)
        {
            var @events = this._eventStore.ReadPartial(global::PureES.Core.Direction.Forwards, streamId, requiredRevision, cancellationToken);
            return Create(@events, cancellationToken);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public async global::System.Threading.Tasks.Task<global::PureES.Core.Tests.Models.TestAggregate> Create(global::System.Collections.Generic.IAsyncEnumerable<global::PureES.Core.EventEnvelope> @events, CancellationToken cancellationToken)
        {
            await using (var enumerator = @events.GetAsyncEnumerator(cancellationToken))
            {
                if (!await enumerator.MoveNextAsync())
                {
                    throw new ArgumentException("Stream is empty", nameof(@events));
                }
                global::PureES.Core.Tests.Models.TestAggregate current;
                TestAggregateAggregateStore_Services services = this._services.GetRequiredService<TestAggregateAggregateStore_Services>();
                switch (enumerator.Current.Event)
                {
                    case global::PureES.Core.Tests.Models.Events.Created e:
                    {
                        current = global::PureES.Core.Tests.Models.TestAggregate.When(
                            new global::PureES.Core.EventEnvelope<global::PureES.Core.Tests.Models.Events.Created, global::PureES.Core.Tests.Models.Metadata>(enumerator.Current));
                        break;
                    }
                    default:
                    {
                        var eventType = global::PureES.Core.BasicEventTypeMap.GetTypeName(enumerator.Current.Event.GetType());
                        var aggregateType = global::PureES.Core.BasicEventTypeMap.GetTypeName(typeof(global::PureES.Core.Tests.Models.TestAggregate));
                        throw new NotImplementedException($"No suitable CreateWhen method found for event '{eventType}' on '{aggregateType}'");
                    }
                }
                current.GlobalWhen(enumerator.Current, cancellationToken);
                await current.GlobalWhenAsync(enumerator.Current, services.S0);
                while (await enumerator.MoveNextAsync())
                {
                    switch (enumerator.Current.Event)
                    {
                        case global::PureES.Core.Tests.Models.Events.Updated e:
                        {
                            current.When(e, services.S1);
                            break;
                        }
                        case int e:
                        {
                            await current.When(
                                new global::PureES.Core.Tests.Models.EventEnvelope<int>(enumerator.Current),
                                services.S0);
                            break;
                        }
                        case global::PureES.Core.Tests.Models.Events.Updated e:
                        {
                            current = global::PureES.Core.Tests.Models.TestAggregate.UpdateWhenStatic(e, current);
                            break;
                        }
                        default:
                        {
                            var eventType = global::PureES.Core.BasicEventTypeMap.GetTypeName(enumerator.Current.Event.GetType());
                            var aggregateType = global::PureES.Core.BasicEventTypeMap.GetTypeName(typeof(global::PureES.Core.Tests.Models.TestAggregate));
                            throw new NotImplementedException($"No suitable UpdateWhen method found for event '{eventType}' on '{aggregateType}'");
                        }
                    }
                    current.GlobalWhen(enumerator.Current, cancellationToken);
                    await current.GlobalWhenAsync(enumerator.Current, services.S0);
                }
                return current;
            }
        }
    }
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PureES.SourceGenerator", "1.0.0.0")]
    internal class TestAggregateAggregateStore_Services
    {
        public readonly global::Microsoft.Extensions.Logging.ILoggerFactory S0;
        public readonly global::System.IServiceProvider S1;


        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TestAggregateAggregateStore_Services(
            global::Microsoft.Extensions.Logging.ILoggerFactory s0,
            global::System.IServiceProvider s1)
        {
            this.S0 = s0;
            this.S1 = s1;
        }
    }
}
