//HintName: PureES.DependencyInjection.PureESServiceCollectionExtensions.g.cs
// <auto-generated/>
// This file was automatically generated by the PureES source generator.
// Do not edit this file manually since it will be automatically overwritten.
// ReSharper disable All

#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace PureES.DependencyInjection
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PureES.SourceGenerator", "1.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal class PureESServiceCollectionExtensions
    {

        [global::System.Diagnostics.DebuggerStepThroughAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static void RegisterServices(IServiceCollection services)
        {
            if (services == null)
            {
                throw new ArgumentNullException(nameof(services));
            }

            var registeredServices = new global::System.Collections.Generic.HashSet<global::System.Type>();
            var registeredImplementations = new global::System.Collections.Generic.HashSet<global::System.Type>();
            foreach (var s in services)
            {
                registeredServices.Add(s.ServiceType);
                if (s.ImplementationType != null)
                {
                    registeredImplementations.Add(s.ImplementationType);
                }
            }
            // Aggregate: PureES.Core.Tests.Models.TestAggregates.Aggregate. Command handlers: 4
            if (registeredServices.Contains(global::PureES.Core.IAggregateStore<global::PureES.Core.Tests.Models.TestAggregates.Aggregate>)
            {
                services.RemoveAll(global::PureES.Core.IAggregateStore<global::PureES.Core.Tests.Models.TestAggregates.Aggregate>);
            }
            services.Add(new ServiceDescriptor(
                serviceType: global::PureES.Core.IAggregateStore<global::PureES.Core.Tests.Models.TestAggregates.Aggregate>,
                implementationType: typeof(global::PureES.AggregateStores.AggregateAggregateStore),
                serviceLifetime: ServiceLifetime.Transient));
            if (registeredServices.Contains(global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.Create>)
            {
                services.RemoveAll(global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.Create>);
            }
            services.Add(new ServiceDescriptor(
                serviceType: global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.Create>,
                implementationType: typeof(global::PureES.CommandHandlers.CreateCommandHandler),
                serviceLifetime: ServiceLifetime.Transient));
            if (registeredServices.Contains(global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.Update>)
            {
                services.RemoveAll(global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.Update>);
            }
            services.Add(new ServiceDescriptor(
                serviceType: global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.Update>,
                implementationType: typeof(global::PureES.CommandHandlers.UpdateCommandHandler),
                serviceLifetime: ServiceLifetime.Transient));
            if (registeredServices.Contains(global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.UpdateConstantStream>)
            {
                services.RemoveAll(global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.UpdateConstantStream>);
            }
            services.Add(new ServiceDescriptor(
                serviceType: global::PureES.Core.ICommandHandler<global::PureES.Core.Tests.Models.Commands.UpdateConstantStream>,
                implementationType: typeof(global::PureES.CommandHandlers.UpdateConstantStreamCommandHandler),
                serviceLifetime: ServiceLifetime.Transient));
            if (registeredServices.Contains(global::PureES.Core.ICommandHandler<int[]>)
            {
                services.RemoveAll(global::PureES.Core.ICommandHandler<int[]>);
            }
            services.Add(new ServiceDescriptor(
                serviceType: global::PureES.Core.ICommandHandler<int[]>,
                implementationType: typeof(global::PureES.CommandHandlers.CommandHandler),
                serviceLifetime: ServiceLifetime.Transient));

            // Event Handlers. Count: 2

            if (!registeredImplementations.Contains(typeof(global::PureES.EventHandlers.CreatedEventHandler)))
            {
                services.Add(new ServiceDescriptor(
                    serviceType: global::PureES.Core.IEventHandler<global::PureES.Core.Tests.Models.Events.Created>,
                    implementationType: typeof(global::PureES.EventHandlers.CreatedEventHandler),
                    serviceLifetime: ServiceLifetime.Transient));
            }

            if (!registeredImplementations.Contains(typeof(global::PureES.EventHandlers.UpdatedEventHandler)))
            {
                services.Add(new ServiceDescriptor(
                    serviceType: global::PureES.Core.IEventHandler<global::PureES.Core.Tests.Models.Events.Updated>,
                    implementationType: typeof(global::PureES.EventHandlers.UpdatedEventHandler),
                    serviceLifetime: ServiceLifetime.Transient));
            }
            // Event handler parents. Count: 1

            if (!registeredServices.Contains(typeof(global::PureES.Core.Tests.Models.TestAggregates.EventHandlers)))
            {
                services.Add(new ServiceDescriptor(
                    serviceType: typeof(global::PureES.Core.Tests.Models.TestAggregates.EventHandlers),
                    implementationType: typeof(global::PureES.Core.Tests.Models.TestAggregates.EventHandlers),
                    serviceLifetime: ServiceLifetime.Transient));
            }

        }
    }
}
